### ISSUE TITLE
Error: Expected a backslash preceding the semicolon.

### ISSUE THREAD

**Issue by skmail** [alexandr-solovyov/postcss-responsive-properties#6]
Hello, 

Thanks for the nice plugin.

An error thrown "In the title" when trying to integrate with lost plugin 

sample code :
```
aside{
    background: red;
    @lost-column:{
        default:1/2;
    };
}
```

After digging into your code i figured out that the issue is in line 60, the value key value is concatenated with semi-colon ,  when i removed that  concatenation every thing works fine. I don't know if this fix will break other places in your code and i have no idea about PostCSS API to fix the issue.

```
//node_modules/postcss-responsive-properties/index.js
rule.replaceWith({
     type: 'decl',
     prop: rule.name.slice(0, -1),
     value: rule.nodes[0].value + ';'
});
```

Best Regards

**Comment by alex-solovev** [comment]
Hello, sorry for such a late answer.
Few minutes ago I was published new major version of plugin. Now syntax is slightly different: no need to write at-symbol before property name, also I removed dependencies on merge-rules and variables - now it's standalone,  and, of course, your issue was fixed :) Check it if this still make sense.
